name: Build csgo.exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pystray pillow requests
    - run: |
        pyinstaller --onefile --noconsole --icon=icon.ico csgo.py
    - uses: actions/upload-artifact@v4
      with:
        name: csgo-windows
        path: dist/csgo.exe
